INSERT INTO teams VALUES('BE', 'Belenenses SAD', 'Football', 'Estádio do Restelo', 'Portugal');
INSERT INTO teams VALUES('BEN', 'SL Benfica', 'Football', 'Estádio da Luz', 'Portugal');
INSERT INTO teams VALUES('BO', 'Boavista FC', 'Football', 'Estádio do Bessa','Portugal');
INSERT INTO teams VALUES('BR', 'SC Braga', 'football', 'Estádio Municipal de Braga', 'Portugal');
INSERT INTO teams VALUES('DA', 'CD Aves', 'Football', 'Estádio do CD Aves', 'Portugal');
INSERT INTO teams VALUES('FA', 'FC Famalicão', 'Football', 'Estádio Municipal 22 de Junho', 'Portugal');
INSERT INTO teams VALUES('GV', 'Gil Vicente FC', 'Football', 'Estádio Cidade de Barcelos', 'Portugal');
INSERT INTO teams VALUES('MA', 'Marítimo M.', 'Football', 'Estádio do Marítimo', 'Portugal');
INSERT INTO teams VALUES('MO', 'Moreirense', 'Football', 'Parque de Jogos Comendador Joaquim de Almeida Freitas', 'Portugal');
INSERT INTO teams VALUES('PF', 'FC P.Ferreira', 'Football', 'Estádio da Mata Real', 'Portugal');
INSERT INTO teams VALUES('PO', 'FC Porto', 'Football', 'Estádio do Dragão', 'Portugal');
INSERT INTO teams VALUES('LFC', 'Belenenses', 'Football', 'Estádio do Restelo', 'Portugal');
INSERT INTO teams VALUES('RA', 'Rio Ave FC', 'Football', 'Estádio dos Arcos', 'Portugal');
INSERT INTO teams VALUES('SC', 'Santa Clara', 'Football', 'Estádio de São Miguel', 'Portugal');
INSERT INTO teams VALUES('SCP', 'Sporting CP', 'Football', 'Estádio José Alvalade', 'Portugal');
INSERT INTO teams VALUES('TO', 'CD Tondela', 'Football', 'Estádio João Cardoso', 'Portugal');
INSERT INTO teams VALUES('VG', 'Vitória de Guimarães', 'Football', 'Estádio D. Afonso Henriques', 'Portugal');
INSERT INTO teams VALUES('VSE', 'Vitória SC', 'Football', 'Estádio do Bonfim', 'Portugal');
INSERT INTO teams VALUES('POR', 'Portimonense', 'Football', 'Estádio Municipal de Portimão', 'Portugal');
INSERT INTO teams VALUES('MOR', 'Moreirense FC', 'Football', 'Parque de Jogos Comendador Joaquim', 'Portugal');
INSERT INTO teams VALUES('VFC', 'Vitória FC', 'Football', 'Estádio D. Afonso Henriques', 'Portugal');